/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  BrtConfig,
  BrtData,
} from '@bruit/types';

export namespace Components {
  interface BruitIo {
    'config': BrtConfig | string;
    /**
    * field array to add in feedback
    */
    'data': Array<BrtData>;
    /**
    * FN or PROMISE return field array to add in feedback
    */
    'dataFn': () => Array<BrtData> | Promise<Array<BrtData>>;
  }
  interface BruitModal {
    /**
    * called on click on bruit-io init a feedback, wait user submit, send feedback
    */
    'open': (brtConfig?: BrtConfig, data?: BrtData[], dataFn?: () => BrtData[] | Promise<BrtData[]>) => Promise<void>;
  }
  interface BruitRating {
    'color': string;
    'max': number;
    'offColor': string;
    'value': number;
  }
}

declare global {


  interface HTMLBruitIoElement extends Components.BruitIo, HTMLStencilElement {}
  var HTMLBruitIoElement: {
    prototype: HTMLBruitIoElement;
    new (): HTMLBruitIoElement;
  };

  interface HTMLBruitModalElement extends Components.BruitModal, HTMLStencilElement {}
  var HTMLBruitModalElement: {
    prototype: HTMLBruitModalElement;
    new (): HTMLBruitModalElement;
  };

  interface HTMLBruitRatingElement extends Components.BruitRating, HTMLStencilElement {}
  var HTMLBruitRatingElement: {
    prototype: HTMLBruitRatingElement;
    new (): HTMLBruitRatingElement;
  };
  interface HTMLElementTagNameMap {
    'bruit-io': HTMLBruitIoElement;
    'bruit-modal': HTMLBruitModalElement;
    'bruit-rating': HTMLBruitRatingElement;
  }
}

declare namespace LocalJSX {
  interface BruitIo extends JSXBase.HTMLAttributes<HTMLBruitIoElement> {
    'config'?: BrtConfig | string;
    /**
    * field array to add in feedback
    */
    'data'?: Array<BrtData>;
    /**
    * FN or PROMISE return field array to add in feedback
    */
    'dataFn'?: () => Array<BrtData> | Promise<Array<BrtData>>;
    /**
    * emit bruit-error on internal error or config error ex : BruitIo.addEventListener('onError',error=>...)
    */
    'onOnError'?: (event: CustomEvent<any>) => void;
  }
  interface BruitModal extends JSXBase.HTMLAttributes<HTMLBruitModalElement> {
    /**
    * emit bruit-error on internal error or config error ex : BruitIo.addEventListener('onError',error=>...)
    */
    'onOnError'?: (event: CustomEvent<any>) => void;
  }
  interface BruitRating extends JSXBase.HTMLAttributes<HTMLBruitRatingElement> {
    'color'?: string;
    'max'?: number;
    'offColor'?: string;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'value'?: number;
  }

  interface IntrinsicElements {
    'bruit-io': BruitIo;
    'bruit-modal': BruitModal;
    'bruit-rating': BruitRating;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


